import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, Grid } from "@mui/material";

import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { checkUserToken } from "../store/actions/userActions";

import { useTheme } from "@mui/material/styles";
import useMediaQuery from "@mui/material/useMediaQuery";
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';

import FacebookIcon from '@mui/icons-material/Facebook';
import TwitterIcon from '@mui/icons-material/Twitter';
import InstagramIcon from '@mui/icons-material/Instagram';

import MainNavigationDesktop from "../components/navigation/MainNavigationDesktop";
import MainNavigationMobile from "../components/navigation/MainNavigationMobile";
import GlobalLoading from "../components/Progress/GlobalLoading";

export default function Home() {
  const dispatch = useDispatch();
  const userLoggedStatus = useSelector((state) => state.user.userLoggedStatus);

  const theme = useTheme();
  const mobileView = useMediaQuery(theme.breakpoints.down("md"));

  useEffect(() => {
    if (!userLoggedStatus) {
      checkUserToken(dispatch);
    }
  }, [userLoggedStatus]);

  const slideMenu = useSelector((state) => state.homePage.displaySlideMenu);
  const loading = useSelector((state) => state.global.loading);

  return (
    <>
      {loading && <GlobalLoading />}

      <Box>
        <Head>
          <title>SSK || Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
            rel="stylesheet"
          />
        </Head>

        {!mobileView && (
          <>
            <MainNavigationDesktop onHome={true} />
            <Box className={styles.outerWrapper}>
              <Box
                className={styles.wrapper}
                style={slideMenu ? { display: "none" } : { display: "flex" }}
              >
                <Box
                  className={`${styles.slide}`}
                  style={{ backgroundColor: "orange", paddingTop: "120px" }}
                >
                  <Box component="main" className={styles.pageTransitions}>
                    <Box component="section">
                      <Box
                        component="section"
                        className={`${styles.cardOverview} ${styles.gridContainer}`}
                      >
                        <Box
                          component="article"
                          className={styles.cardOverviewContentStart}
                        >
                          <Box
                            component="h1"
                            className={`${styles.cardOverviewContentStartHeading} ${styles.heading2}`}
                          >
                            {
                              "Discover the Life and Work of Srimanta Sankaradev"
                            }
                          </Box>
                          <Box
                            component="p"
                            className={styles.cardOverviewContentStartIntro}
                          >
                            {
                              "Welcome back to the SSK Museum! Plan your visit, book tickets online."
                            }
                          </Box>
                          <Box component="section" className={styles.ctaList}>
                            <Box component="ul">
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/ticket-book"
                                  id={"book_text"}
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Book tickets"}
                                  <ArrowForwardIcon
                                    id={"book_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                          mr={6}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Sangrahalaya.jpg"
                                alt="Sangrahalaya"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/sangrahalaya"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Sangrahalaya"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore the visible demand of portraying the life, work and contributions of Mahapurush Srimanta Sankardev."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                          mr={6}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Lalit_kala.jpg"
                                alt="Lalit Kala"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/lalit-kala"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Lalit Kala"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore SSK's famous platform to the regional community of artists to develop and exhibit their creative talents."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                          mr={6}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Sahitya.jpg"
                                alt="Sahitya"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/sahitya"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Sahitya"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore the prominent dance forms of Assam and other Northeastern States through life-sized models."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={styles.cardOverviewContentEnd}
                          // ml={6}
                        >
                          <Box
                            component="p"
                            className={`${styles.heading4} ${styles.cardOverviewContentEndHeading}`}
                          >
                            {
                              "Explore more about the museum and Srimanta Sankaradev"
                            }
                          </Box>
                          <Box component="section" className={styles.ctaList}>
                            <Box component="ul">
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/art-gallery"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Explore the Art Gallery"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/stories"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Read fascinating story about Srimanta Sankaradev"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/address"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Check our Opening time and Address"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                            </Box>
                          </Box>

                          <Box component="section" className={styles.logoBlock}>
                            <Box
                              component="h3"
                              className={`${styles.heading5} ${styles.logoBlockTitle}`}
                            >
                              {"Our Social media"}
                            </Box>
                            <Box className={styles.logoBlockLogos}>
                              <Box>
                                <FacebookIcon fontSize="large"/>
                              </Box>
                              <Box sx={{ mx: 2, }}>
                                <InstagramIcon fontSize="large"/>
                              </Box>
                              <Box sx={{ mx: 2, }}>
                                <TwitterIcon fontSize="large"/>
                              </Box>
                            </Box>
                          </Box>
                        </Box>
                      </Box>
                    </Box>
                  </Box>
                </Box>
              </Box>
            </Box>
          </>
        )}

        {mobileView && (
          <Box sx={slideMenu ? {backgroundColor: "transparent"} : { backgroundColor: "orange" }}>
            <MainNavigationMobile />

            <Box style={slideMenu ? { display: "none" } : { display: "flex" }}>
              <Box>
              <Box component="main" className={styles.pageTransitions}>
                    <Box component="section">
                      <Box
                        component="section"
                        className={`${styles.cardOverview} ${styles.gridContainer}`}
                      >
                        <Box
                          component="article"
                          className={styles.cardOverviewContentStart}
                        >
                          <Box
                            component="h1"
                            className={`${styles.cardOverviewContentStartHeading} ${styles.heading2}`}
                          >
                            {
                              "Discover the Life and Work of Srimanta Sankaradev"
                            }
                          </Box>
                          <Box
                            component="p"
                            className={styles.cardOverviewContentStartIntro}
                          >
                            {
                              "Welcome back to the SSK Museum! Plan your visit, book tickets online."
                            }
                          </Box>
                          <Box component="section" className={styles.ctaList}>
                            <Box component="ul">
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/ticket-book"
                                  id={"book_text"}
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Book tickets"}
                                  <ArrowForwardIcon
                                    id={"book_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                          mb={6}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Sangrahalaya.jpg"
                                alt="Sangrahalaya"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/sangrahalaya"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Sangrahalaya"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore the visible demand of portraying the life, work and contributions of Mahapurush Srimanta Sankardev."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                          mb={6}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Lalit_kala.jpg"
                                alt="Lalit Kala"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/lalit-kala"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Lalit Kala"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore SSK's famous platform to the regional community of artists to develop and exhibit their creative talents."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={`${styles.teaser} ${styles.teaserCard} ${styles.pageTeaser}`}
                        >
                          <Box className={styles.teaserCardImage}>
                            <Box
                              className={`${styles.focusPointImage} ${styles.objectFitContainer} ${styles.cover}`}
                            >
                              <Box
                                component="img"
                                src="/Sahitya.jpg"
                                alt="Sahitya"
                                className={styles.lazyImage}
                              />
                            </Box>
                          </Box>

                          <Box
                            component="a"
                            href="/sahitya"
                            className={styles.teaserCardContent}
                          >
                            <Box
                              component="p"
                              className={styles.teaserCardLabel}
                            >
                              {"Always on view"}
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.teaserCardTitle} ${styles.heading5}`}
                            >
                              {"Sahitya"}
                            </Box>
                            <Box
                              component="p"
                              className={styles.teaserCardText}
                            >
                              {
                                "Explore the prominent dance forms of Assam and other Northeastern States through life-sized models."
                              }
                            </Box>
                            <Box
                              component="p"
                              className={`${styles.link} ${styles.link_Icon_Right}`}
                            >
                              {"Explore"}
                              <ArrowForwardIcon
                                id={"donate_icon"}
                                className={styles.icon_Arrow_Right_Medium}
                              />
                            </Box>
                          </Box>
                        </Box>

                        <Box
                          component="article"
                          className={styles.cardOverviewContentEnd}
                        >
                          <Box
                            component="p"
                            className={`${styles.heading4} ${styles.cardOverviewContentEndHeading}`}
                          >
                            {
                              "Explore more about the museum and Srimanta Sankaradev"
                            }
                          </Box>
                          <Box component="section" className={styles.ctaList}>
                            <Box component="ul">
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/art-gallery"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Explore the Art Gallery"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/stories"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Read fascinating story about Srimanta Sankaradev"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                              <Box
                                component="li"
                                className={styles.ctaListItem}
                              >
                                <Box
                                  component="a"
                                  href="/address"
                                  className={`${styles.link} ${styles.link_Icon_Left}`}
                                >
                                  {"Check our Opening time and Address"}
                                  <ArrowForwardIcon
                                    id={"donate_icon"}
                                    className={styles.icon_Arrow_Right_Medium}
                                  />
                                </Box>
                              </Box>
                            </Box>
                          </Box>

                          <Box component="section" className={styles.logoBlock}>
                            <Box
                              component="h3"
                              className={`${styles.heading5} ${styles.logoBlockTitle}`}
                            >
                              {"Our Social media"}
                            </Box>
                            <Box className={styles.logoBlockLogos}>
                              <Box>
                                <FacebookIcon fontSize="large"/>
                              </Box>
                              <Box sx={{ my: 2, }}>
                                <InstagramIcon fontSize="large"/>
                              </Box>
                              <Box sx={{ my: 2, }}>
                                <TwitterIcon fontSize="large"/>
                              </Box>
                            </Box>
                          </Box>
                        </Box>
                      </Box>
                    </Box>
                  </Box>
              </Box>
            </Box>
          </Box>
        )}
      </Box>
    </>
  );
}
